name: Deploy to GitHub Pages

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3 # node16 runtime by default
      - name: yarn install & build/export
        run: |
          yarn
          yarn build
          yarn export
      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
